# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

primary_region = 'arn'

[build]
  image = 'codeberg.org/readeck/readeck:latest'

[processes]
  web = '/bin/readeck serve -config config.toml'

[[mounts]]
  source = 'readeck_data'
  destination = '/readeck'
  initial_size = '1GB'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '3GB'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

  [http_service.concurrency]
    type = 'requests'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['web']
